image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - before: nvm install lts/* && nvm use lts/* && npm install --global yarn
    init: yarn install # echo 'init script' # runs during prebuild
    command: yarn netlify login && yarn develop # echo 'start script'
