[build]
  publish = "public"
  command = "yarn build"
  context = "production"
  # functions = "functions"
[build.environment]
  # YARN_VERSION = "1.9.4"
  YARN_VERSION = "1.16.0"
  YARN_FLAGS = "--no-ignore-optional"
